# Generated by Django 4.2.7 on 2023-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(default='musiblog', max_length=255),
        ),
    ]
