# Generated by Django 4.2.7 on 2023-12-16 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musiblog', '0002_post_titulo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_post',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(max_length=255),
        ),
    ]
