# Generated by Django 4.2.7 on 2023-12-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiblog', '0005_rename_categorias_categories_remove_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Haz click para leer el post!', max_length=255),
        ),
    ]
