# Generated by Django 4.2.7 on 2023-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiblog', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/perfil/'),
        ),
    ]
