# Generated by Django 4.2.7 on 2023-12-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiblog', '0010_alter_perfil_imagen_perfil_comentar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentar',
            new_name='Comment',
        ),
    ]
